name: CI/CD Direct Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build Docker image (optional)
      run: docker build -t myapp:latest .

    - name: Deploy to Ubuntu server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_HOST }}      # Server public IP
        username: ${{ secrets.SSH_USER }}  # SSH user
        key: ${{ secrets.SSH_KEY }}        # Private key secret
        port: 22                         # SSH port if not 22
        script: |
          cd /home/${{ secrets.SSH_USER }}/myapp/Sales-Demand-Forecasting-API

          git pull || echo "Repo not cloned yet"

          docker stop myapp || true
          docker rm myapp || true

          docker build -t myapp:latest .

          docker run -d --name myapp -p 8001:8001 myapp:latest
